// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrTBTxwyweMwFyAmRN551pRjvvTJTUnLA',
    appId: '1:573834799227:web:0c036d82f041c3762bdade',
    messagingSenderId: '573834799227',
    projectId: 'where-s-app-6e4f5',
    authDomain: 'where-s-app-6e4f5.firebaseapp.com',
    storageBucket: 'where-s-app-6e4f5.appspot.com',
    measurementId: 'G-XKDDQ7PSVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAO0aJcC1czr747Q7bQZGMG3FIF1jQaaU',
    appId: '1:573834799227:android:9b11aefbf3d234782bdade',
    messagingSenderId: '573834799227',
    projectId: 'where-s-app-6e4f5',
    storageBucket: 'where-s-app-6e4f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbT-eL1Fddjy9QCSzisOg4ACzEKU2QAjo',
    appId: '1:573834799227:ios:4e495479afe802d02bdade',
    messagingSenderId: '573834799227',
    projectId: 'where-s-app-6e4f5',
    storageBucket: 'where-s-app-6e4f5.appspot.com',
    iosClientId: '573834799227-p77vns37vdv7i7usm9ojtbqc809ccf3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheresapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbT-eL1Fddjy9QCSzisOg4ACzEKU2QAjo',
    appId: '1:573834799227:ios:4e495479afe802d02bdade',
    messagingSenderId: '573834799227',
    projectId: 'where-s-app-6e4f5',
    storageBucket: 'where-s-app-6e4f5.appspot.com',
    iosClientId: '573834799227-p77vns37vdv7i7usm9ojtbqc809ccf3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheresapp',
  );
}
