// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPz-R5A7n0CK3LwGGni1_BWL7QSWxaa5U',
    appId: '1:892775089173:web:03362e64103462e23bba1c',
    messagingSenderId: '892775089173',
    projectId: 'where-s-app',
    authDomain: 'where-s-app.firebaseapp.com',
    storageBucket: 'where-s-app.appspot.com',
    measurementId: 'G-QCF79KE88N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnRUfOhkt116q2N3vMqaTRX87reVq1PsA',
    appId: '1:892775089173:android:1afc4c6d63ef88093bba1c',
    messagingSenderId: '892775089173',
    projectId: 'where-s-app',
    storageBucket: 'where-s-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YC9R--1-Q8aHadnAr_BFJVRv3B7Kohc',
    appId: '1:892775089173:ios:4edd2ca17fdb91dc3bba1c',
    messagingSenderId: '892775089173',
    projectId: 'where-s-app',
    storageBucket: 'where-s-app.appspot.com',
    iosClientId: '892775089173-atpig1oqqa35vugnjd3hvbpkugn9ncs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheresapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2YC9R--1-Q8aHadnAr_BFJVRv3B7Kohc',
    appId: '1:892775089173:ios:4edd2ca17fdb91dc3bba1c',
    messagingSenderId: '892775089173',
    projectId: 'where-s-app',
    storageBucket: 'where-s-app.appspot.com',
    iosClientId: '892775089173-atpig1oqqa35vugnjd3hvbpkugn9ncs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheresapp',
  );
}
